# GDScript
[[language]]
name = "gdscript"
language-servers = ["gdscript-lsp"]

[language-server.gdscript-lsp]
command = "nc"
args = ["127.0.0.1", "6005"]
language-id = "gdscript"

# Nix
[[language]]
name = "nix"
auto-format = true

[language-server.nixfmt]
command = "nixfmt"


[language-server.rust-analyzer.config.inlayHints]
closingBraceHints.minLines = 10
closureReturnTypeHints.enable = "with_block"
discriminantHints.enable = "fieldless"
expressionAdjustmentHints.enable = "never"
expressionAdjustmentHints.hideOutsideUnsafe = false
expressionAdjustmentHints.mode = "prefer_prefix"
lifetimeElisionHints.enable = "skip_trivial"
typeHints.hideClosureInitialization = false