# GDScript
[[language]]
name = "gdscript"
language-servers = ["gdscript-lsp"]

[language-server.gdscript-lsp]
command = "nc"
args = ["127.0.0.1", "6005"]
language-id = "gdscript"

# Nix
[[language]]
name = "nix"
auto-format = true

[language-server.nixfmt]
command = "nixfmt"
