# Generated by ./pia-server-list-generator.sh

[
  { id = "PIA - US Seattle";
    uuid = "4c2160e1-0146-54c1-8f86-6ccde5765433";
    remote = "us-seattle.privacy.network";
  }
  { id = "PIA - AU Sydney";
    uuid = "3d5511f8-1be3-525c-a517-63e9ead8aa5c";
    remote = "au-sydney.privacy.network";
  }
  { id = "PIA - Brazil";
    uuid = "342eb48c-8974-57e7-9a52-93a9ab2cb378";
    remote = "br.privacy.network";
  }
  { id = "PIA - Saudi Arabia";
    uuid = "b663b897-2583-5b84-abca-0f25766b4983";
    remote = "saudiarabia.privacy.network";
  }
  { id = "PIA - UK Streaming Optimized";
    uuid = "559b77e9-6129-595f-a98f-ad5c34919727";
    remote = "uk-2.privacy.network";
  }
  { id = "PIA - US South Carolina";
    uuid = "f94e461d-2cef-506c-92a0-20a671865451";
    remote = "us-south-carolina-pf.privacy.network";
  }
  { id = "PIA - US Connecticut";
    uuid = "32b804ab-4562-54d7-bc14-2d4717e14d4b";
    remote = "us-connecticut-pf.privacy.network";
  }
  { id = "PIA - Taiwan";
    uuid = "bac5ab7c-c8a9-58f5-bcf5-c8e9a53db7ee";
    remote = "taiwan.privacy.network";
  }
  { id = "PIA - US New Mexico";
    uuid = "3ff28ca6-7c56-57a9-b10c-c08dbf17837f";
    remote = "us-new-mexico-pf.privacy.network";
  }
  { id = "PIA - Belgium";
    uuid = "1e255262-acb1-59bf-b916-19eb735d0230";
    remote = "brussels.privacy.network";
  }
  { id = "PIA - US Alabama";
    uuid = "5074483f-0161-515d-b467-5c844c7dd696";
    remote = "us-alabama-pf.privacy.network";
  }
  { id = "PIA - US North Dakota";
    uuid = "a89a4d80-8405-5add-b87c-f8db9a616a2c";
    remote = "us-north-dakota-pf.privacy.network";
  }
  { id = "PIA - Venezuela";
    uuid = "f80fb2a3-d5cd-525f-8ca9-000948fff282";
    remote = "venezuela.privacy.network";
  }
  { id = "PIA - CA Toronto";
    uuid = "a4916830-8263-5bbb-b7f8-8fdadb3e0dc5";
    remote = "ca-toronto.privacy.network";
  }
  { id = "PIA - Bulgaria";
    uuid = "cf4e3508-02f7-5faa-aeb3-d3df4a0ad423";
    remote = "sofia.privacy.network";
  }
  { id = "PIA - US Wilmington";
    uuid = "654d4bc0-8cbf-5b88-a487-a70b8fa28718";
    remote = "us-wilmington.privacy.network";
  }
  { id = "PIA - US Denver";
    uuid = "309fc6a0-bc64-5e39-ab15-dd368a9a0a5a";
    remote = "us-denver.privacy.network";
  }
  { id = "PIA - US Houston";
    uuid = "37c0777b-8dc6-5a80-aa9a-498209511954";
    remote = "us-houston.privacy.network";
  }
  { id = "PIA - Lithuania";
    uuid = "4bd23495-412f-583d-9764-c96e705f2c1f";
    remote = "lt.privacy.network";
  }
  { id = "PIA - US South Dakota";
    uuid = "2c1e86e4-de4e-5c11-b6ad-457817d9ace2";
    remote = "us-south-dakota-pf.privacy.network";
  }
  { id = "PIA - AU Perth";
    uuid = "fb242da2-6e3f-5560-ae99-fbf15f945850";
    remote = "aus-perth.privacy.network";
  }
  { id = "PIA - US Silicon Valley";
    uuid = "62d6bef6-1fda-5df1-b61c-8c22cbc83171";
    remote = "us-siliconvalley.privacy.network";
  }
  { id = "PIA - US Massachusetts";
    uuid = "985ab90b-e210-5a95-a74b-2d4e58effc2c";
    remote = "us-massachusetts-pf.privacy.network";
  }
  { id = "PIA - NL Netherlands Streaming Optimized";
    uuid = "e8f27db4-5856-5730-b15b-98b9e47050d6";
    remote = "nl-netherlands-so.privacy.network";
  }
  { id = "PIA - US Louisiana";
    uuid = "360e2d0d-bd17-5fa2-b837-40160086fda5";
    remote = "us-louisiana-pf.privacy.network";
  }
  { id = "PIA - Uruguay";
    uuid = "a90a597e-db31-54c1-8a5d-b96c7d77f432";
    remote = "uy-uruguay-pf.privacy.network";
  }
  { id = "PIA - Nigeria";
    uuid = "ba334622-c868-5399-bee7-cbcb89f44a37";
    remote = "nigeria.privacy.network";
  }
  { id = "PIA - US Montana";
    uuid = "1b527f2a-52ca-55ca-9c47-d7a23dcd792d";
    remote = "us-montana-pf.privacy.network";
  }
  { id = "PIA - Mexico";
    uuid = "f2a6fe0e-3685-585f-a35a-bf52c12f5ef2";
    remote = "mexico.privacy.network";
  }
  { id = "PIA - Australia Streaming Optimized";
    uuid = "a9099f45-fd36-5091-9e3f-b068a4946a80";
    remote = "au-australia-so.privacy.network";
  }
  { id = "PIA - Morocco";
    uuid = "e52e15db-04b6-5d3c-9dce-6a3af6b93acf";
    remote = "morocco.privacy.network";
  }
  { id = "PIA - CA Vancouver";
    uuid = "4fd447e3-7274-55c9-b625-5b085419ef09";
    remote = "ca-vancouver.privacy.network";
  }
  { id = "PIA - Georgia";
    uuid = "6e8c80d0-64d6-5615-9456-bf39e4e7c961";
    remote = "georgia.privacy.network";
  }
  { id = "PIA - India";
    uuid = "7dfcbd7a-d749-5f34-8955-b4a0205e579f";
    remote = "in.privacy.network";
  }
  { id = "PIA - UK Manchester";
    uuid = "88ebd5ae-58e5-5bdd-b633-17883657f459";
    remote = "uk-manchester.privacy.network";
  }
  { id = "PIA - Latvia";
    uuid = "6e698f50-c26d-53d9-a724-037fce4a4512";
    remote = "lv.privacy.network";
  }
  { id = "PIA - Liechtenstein";
    uuid = "d39b8ed2-98c3-51b5-b020-59af015ddd3b";
    remote = "liechtenstein.privacy.network";
  }
  { id = "PIA - US Florida";
    uuid = "7e9b3976-ae1b-5021-8c85-d8d3f2099dda";
    remote = "us-florida.privacy.network";
  }
  { id = "PIA - Romania";
    uuid = "09d8525d-28f1-5f11-bac6-d7a5b006f683";
    remote = "ro.privacy.network";
  }
  { id = "PIA - Monaco";
    uuid = "396c1eaa-7b07-5b63-b5fa-13c30e4f5c88";
    remote = "monaco.privacy.network";
  }
  { id = "PIA - Sri Lanka";
    uuid = "7fc98895-1836-523c-82a0-418543ad0c1c";
    remote = "srilanka.privacy.network";
  }
  { id = "PIA - US Iowa";
    uuid = "b25f4d30-631e-5ac5-9c84-c2ca21b9c553";
    remote = "us-iowa-pf.privacy.network";
  }
  { id = "PIA - Cambodia";
    uuid = "30f1a66c-83a8-5c31-800a-6abb31ac1c27";
    remote = "cambodia.privacy.network";
  }
  { id = "PIA - Peru";
    uuid = "d2f28129-b721-5626-8695-c3185fbfbc57";
    remote = "pe-peru-pf.privacy.network";
  }
  { id = "PIA - US Chicago";
    uuid = "0851c0bc-fe05-5af8-b4af-143d90c2b83e";
    remote = "us-chicago.privacy.network";
  }
  { id = "PIA - US Idaho";
    uuid = "16bf5ee7-e67e-5f0d-9e16-f563b3300634";
    remote = "us-idaho-pf.privacy.network";
  }
  { id = "PIA - US West";
    uuid = "24066b19-ecb0-50a7-9c84-99e10d6a8d44";
    remote = "us3.privacy.network";
  }
  { id = "PIA - Andorra";
    uuid = "3e433456-b566-58e9-9a69-4cdd10fb8f73";
    remote = "ad.privacy.network";
  }
  { id = "PIA - Turkey";
    uuid = "66cca673-fd4f-514c-a6a9-bc825974e6be";
    remote = "tr.privacy.network";
  }
  { id = "PIA - AU Melbourne";
    uuid = "d1ca6af6-7070-5c5d-a7d2-1a121c905fb5";
    remote = "aus-melbourne.privacy.network";
  }
  { id = "PIA - Bahamas";
    uuid = "78d9c051-1f2e-5f84-9102-c37b59a7f26f";
    remote = "bahamas.privacy.network";
  }
  { id = "PIA - ES Valencia";
    uuid = "c8064bde-d417-54ab-bc92-bd49ad961e08";
    remote = "es-valencia.privacy.network";
  }
  { id = "PIA - US Pennsylvania";
    uuid = "558ff041-dff9-5709-8bf5-aa631524ba8b";
    remote = "us-pennsylvania-pf.privacy.network";
  }
  { id = "PIA - Cyprus";
    uuid = "2485eef3-b792-5c35-9370-ca4805762db7";
    remote = "cyprus.privacy.network";
  }
  { id = "PIA - US Oregon";
    uuid = "8789aa33-a5f1-57ab-baa9-1e8868a83c5b";
    remote = "us-oregon-pf.privacy.network";
  }
  { id = "PIA - US Indiana";
    uuid = "e75d6882-4885-5db9-a214-50e713d149b2";
    remote = "us-indiana-pf.privacy.network";
  }
  { id = "PIA - Ecuador";
    uuid = "40808a2a-978b-5c20-97cb-f35e9fa93c7e";
    remote = "ec-ecuador-pf.privacy.network";
  }
  { id = "PIA - US North Carolina";
    uuid = "910fdbae-15ec-504e-a46e-f2ebf79fd2d4";
    remote = "us-north-carolina-pf.privacy.network";
  }
  { id = "PIA - US Vermont";
    uuid = "b70e7911-d99e-58aa-8ff8-68f8712841a2";
    remote = "us-vermont-pf.privacy.network";
  }
  { id = "PIA - US Kentucky";
    uuid = "6a6992fa-0d4f-5ff0-9400-631dbe3f69e5";
    remote = "us-kentucky-pf.privacy.network";
  }
  { id = "PIA - Chile";
    uuid = "be0ae1ec-feb7-5d15-92e1-7f6399321fa0";
    remote = "santiago.privacy.network";
  }
  { id = "PIA - US East";
    uuid = "53222e09-4bb0-5a57-becb-3c1977f27231";
    remote = "us-newjersey.privacy.network";
  }
  { id = "PIA - Macao";
    uuid = "a8633764-696e-5d01-b6fd-b0784b2cd002";
    remote = "macau.privacy.network";
  }
  { id = "PIA - US California";
    uuid = "3b17bdf2-77b3-5e52-b3f6-4a725feaf203";
    remote = "us-california.privacy.network";
  }
  { id = "PIA - Qatar";
    uuid = "6e62ff8b-e89d-561c-a38d-321ff7732a26";
    remote = "qatar.privacy.network";
  }
  { id = "PIA - Indonesia";
    uuid = "29b99620-dc05-54fc-889e-cc7b7c67afe2";
    remote = "jakarta.privacy.network";
  }
  { id = "PIA - UK London";
    uuid = "d2fa7848-9b97-52ab-87d8-f7ff8ec8a4dc";
    remote = "uk-london.privacy.network";
  }
  { id = "PIA - DK Copenhagen";
    uuid = "9ef22733-a349-5f99-ab27-23775f5f25d2";
    remote = "denmark.privacy.network";
  }
  { id = "PIA - Albania";
    uuid = "b3bd6605-e782-5866-a5a5-769ef23a696a";
    remote = "al.privacy.network";
  }
  { id = "PIA - DE Germany Streaming Optimized";
    uuid = "db87cca3-c3b5-5269-af70-0a1dbb10f043";
    remote = "de-germany-so.privacy.network";
  }
  { id = "PIA - US Alaska";
    uuid = "c8f643a0-215e-589a-a8d4-23bd1e1a88fd";
    remote = "us-alaska-pf.privacy.network";
  }
  { id = "PIA - SE Streaming Optimized";
    uuid = "4f7ccc98-9d45-5da3-9dd6-43f79f6e03ed";
    remote = "sweden-2.privacy.network";
  }
  { id = "PIA - DE Frankfurt";
    uuid = "6395d641-ad1a-5a2e-9626-1baf14ec77d5";
    remote = "de-frankfurt.privacy.network";
  }
  { id = "PIA - South Korea";
    uuid = "2565f938-33b6-5dd1-8e57-b881785ccf72";
    remote = "kr-south-korea-pf.privacy.network";
  }
  { id = "PIA - Greenland";
    uuid = "e1ccc5bf-c07f-5503-a3af-0a9f91858899";
    remote = "greenland.privacy.network";
  }
  { id = "PIA - Hong Kong";
    uuid = "be254ec8-99a3-59b6-aa63-c04b435a3f8b";
    remote = "hk.privacy.network";
  }
  { id = "PIA - Colombia";
    uuid = "3e8bd231-d8e2-5f0f-8ea2-8282bafed509";
    remote = "bogota.privacy.network";
  }
  { id = "PIA - US Tennessee";
    uuid = "05e39729-d771-5588-a404-0508ce011ad9";
    remote = "us-tennessee-pf.privacy.network";
  }
  { id = "PIA - IT Streaming Optimized";
    uuid = "0e7b6859-9c8a-5fc6-9681-ede4018a929f";
    remote = "italy-2.privacy.network";
  }
  { id = "PIA - US Las Vegas";
    uuid = "914adb93-41f5-5653-906a-7e94e3520ffd";
    remote = "us-lasvegas.privacy.network";
  }
  { id = "PIA - AU Brisbane";
    uuid = "e9715a67-2dff-5458-869f-a68cf81b074b";
    remote = "au-brisbane-pf.privacy.network";
  }
  { id = "PIA - US Honolulu";
    uuid = "867c1218-5b90-5463-9e01-8e6460d892c1";
    remote = "us-honolulu.privacy.network";
  }
  { id = "PIA - US Wisconsin";
    uuid = "a071369b-7164-58ab-94d6-95a3d2af2bc9";
    remote = "us-wisconsin-pf.privacy.network";
  }
  { id = "PIA - US New York";
    uuid = "c42f8a48-b7af-58e2-814b-08d1d100eb66";
    remote = "us-newyorkcity.privacy.network";
  }
  { id = "PIA - Austria";
    uuid = "6f40de07-0e31-5af6-bd3e-b69ce46e0fdd";
    remote = "austria.privacy.network";
  }
  { id = "PIA - Nepal";
    uuid = "909ff4b0-9fb6-53f2-9e2b-4d4ba0e2cc73";
    remote = "np-nepal-pf.privacy.network";
  }
  { id = "PIA - Isle of Man";
    uuid = "9a775598-7b62-570e-a561-a8784a85f6d2";
    remote = "man.privacy.network";
  }
  { id = "PIA - Montenegro";
    uuid = "ab7e4f24-c966-5758-854c-c00719ac2c8a";
    remote = "montenegro.privacy.network";
  }
  { id = "PIA - ES Madrid";
    uuid = "4116d6ea-5e50-5239-8a05-31b88bbd6a0d";
    remote = "spain.privacy.network";
  }
  { id = "PIA - US West Virginia";
    uuid = "c18c984d-11a3-581c-84b0-dbc12e037195";
    remote = "us-west-virginia-pf.privacy.network";
  }
  { id = "PIA - US Ohio";
    uuid = "f6e86cad-1aee-5c4e-8949-d9149a098634";
    remote = "us-ohio-pf.privacy.network";
  }
  { id = "PIA - US Wyoming";
    uuid = "2d045729-ddd4-5604-96f7-d0fa4d59788a";
    remote = "us-wyoming-pf.privacy.network";
  }
  { id = "PIA - SE Stockholm";
    uuid = "b01b1da5-d9a8-5f1e-b138-4eb3d4f47ff6";
    remote = "sweden.privacy.network";
  }
  { id = "PIA - US Atlanta";
    uuid = "19219f7f-f4fd-541c-b27f-8fe9636573b8";
    remote = "us-atlanta.privacy.network";
  }
  { id = "PIA - Ukraine";
    uuid = "3078355f-5755-5f6d-b06d-66f1ba54d268";
    remote = "ua.privacy.network";
  }
  { id = "PIA - Mongolia";
    uuid = "2abd2a9e-20d2-5505-9197-f05e5a046995";
    remote = "mongolia.privacy.network";
  }
  { id = "PIA - US Minnesota";
    uuid = "1087a550-e978-55cb-8324-8f4a42b43780";
    remote = "us-minnesota-pf.privacy.network";
  }
  { id = "PIA - Norway";
    uuid = "acd452d7-0050-53a7-8014-6b51d09e9cf9";
    remote = "no.privacy.network";
  }
  { id = "PIA - Bolivia";
    uuid = "7e9b421c-dd09-5a7d-ac5d-b200c5512263";
    remote = "bo-bolivia-pf.privacy.network";
  }
  { id = "PIA - US Salt Lake City";
    uuid = "422c870e-470a-51e0-bc11-a78f24a6d767";
    remote = "us-saltlakecity.privacy.network";
  }
  { id = "PIA - US Arkansas";
    uuid = "7ed38489-61bb-53ba-8d9c-bdee8d1f2e8c";
    remote = "us-arkansas-pf.privacy.network";
  }
  { id = "PIA - FI Helsinki";
    uuid = "273837fb-3f10-5a36-b44a-22e164dc3bda";
    remote = "fi.privacy.network";
  }
  { id = "PIA - Poland";
    uuid = "6622e586-91fb-58ff-bed3-1779d4b173da";
    remote = "poland.privacy.network";
  }
  { id = "PIA - US Oklahoma";
    uuid = "c03f406b-3f5a-51e8-9a1f-25904a7867de";
    remote = "us-oklahoma-pf.privacy.network";
  }
  { id = "PIA - Ireland";
    uuid = "cc7fd69c-90dc-5562-9350-bf3862261bf9";
    remote = "ireland.privacy.network";
  }
  { id = "PIA - New Zealand";
    uuid = "63e49f5f-978c-5c18-9c9a-5369ff83a973";
    remote = "nz.privacy.network";
  }
  { id = "PIA - Netherlands";
    uuid = "3f315b3f-5a87-57fc-bf1e-924eb3cf7b37";
    remote = "nl-amsterdam.privacy.network";
  }
  { id = "PIA - Luxembourg";
    uuid = "022cd6af-1d3f-5088-9d48-521bbfd08e32";
    remote = "lu.privacy.network";
  }
  { id = "PIA - JP Tokyo";
    uuid = "49b1b2c8-9a66-50f3-b7cd-9fead80d6540";
    remote = "japan.privacy.network";
  }
  { id = "PIA - Czech Republic";
    uuid = "be2ff8e4-e17f-59d8-89c4-e0324172c0a5";
    remote = "czech.privacy.network";
  }
  { id = "PIA - US Missouri";
    uuid = "2cdd0333-ddd7-5426-bacd-f80538dd816a";
    remote = "us-missouri-pf.privacy.network";
  }
  { id = "PIA - Bangladesh";
    uuid = "dba3e2b0-7e70-58af-b374-28b68cb8efd6";
    remote = "bangladesh.privacy.network";
  }
  { id = "PIA - Panama";
    uuid = "e747209d-7233-5d38-a184-7567b304dfac";
    remote = "panama.privacy.network";
  }
  { id = "PIA - Croatia";
    uuid = "24f465a7-7a4b-5e25-a8df-b508050c0892";
    remote = "zagreb.privacy.network";
  }
  { id = "PIA - FI Streaming Optimized";
    uuid = "8b9941a4-c00f-5fae-86c0-4703fc2b798b";
    remote = "fi-2.privacy.network";
  }
  { id = "PIA - China";
    uuid = "d2dc1f1f-c420-581f-9403-fe3a3eaa97b3";
    remote = "china.privacy.network";
  }
  { id = "PIA - Bosnia and Herzegovina";
    uuid = "be06465d-e52d-5c30-a1be-b0a77e1e4f70";
    remote = "ba.privacy.network";
  }
  { id = "PIA - IT Milano";
    uuid = "e390a710-756d-556b-979a-f61deb77aced";
    remote = "italy.privacy.network";
  }
  { id = "PIA - US New Hampshire";
    uuid = "dbffca4f-bd93-5d71-94e5-b56ab030f14f";
    remote = "us-new-hampshire-pf.privacy.network";
  }
  { id = "PIA - US Kansas";
    uuid = "b086c2aa-1c3d-5aaa-8113-101a8a853659";
    remote = "us-kansas-pf.privacy.network";
  }
  { id = "PIA - Serbia";
    uuid = "473ece1c-f1f0-5cb2-b81b-3ec4481f55be";
    remote = "rs.privacy.network";
  }
  { id = "PIA - France";
    uuid = "f377f882-7d46-56b5-920f-678204357256";
    remote = "france.privacy.network";
  }
  { id = "PIA - Iceland";
    uuid = "b42125a0-fdf3-5a51-baec-5825eb2bbf4c";
    remote = "is.privacy.network";
  }
  { id = "PIA - Armenia";
    uuid = "250829fd-4a8d-531f-8bf5-84e398d772b2";
    remote = "yerevan.privacy.network";
  }
  { id = "PIA - Malaysia";
    uuid = "1f1ed1bf-9a69-5e22-bcc5-625fcbe7fba5";
    remote = "kualalumpur.privacy.network";
  }
  { id = "PIA - US Nebraska";
    uuid = "5d837af3-afcb-5190-900b-6b37cfb438ab";
    remote = "us-nebraska-pf.privacy.network";
  }
  { id = "PIA - Greece";
    uuid = "93f30469-247b-53dc-9135-4b059e62d4d7";
    remote = "gr.privacy.network";
  }
  { id = "PIA - UK Southampton";
    uuid = "3b21b2cc-77ba-5a70-b078-0703f66d65a2";
    remote = "uk-southampton.privacy.network";
  }
  { id = "PIA - AU Adelaide";
    uuid = "35bd0ed9-6fa3-5fcb-84dc-02bb11dd9511";
    remote = "au-adelaide-pf.privacy.network";
  }
  { id = "PIA - US West Streaming Optimized";
    uuid = "120932c6-f7a1-5aed-b29b-3609ce9827f6";
    remote = "us-streaming-2.privacy.network";
  }
  { id = "PIA - CA Ontario";
    uuid = "51eb93a7-31ec-54fc-acce-cead5cbad0ab";
    remote = "ca-ontario.privacy.network";
  }
  { id = "PIA - Hungary";
    uuid = "09d29cde-4888-5c12-b64c-567a4a3a40ab";
    remote = "hungary.privacy.network";
  }
  { id = "PIA - US Texas";
    uuid = "6e37fa12-7174-5353-afb1-9551f399e3a9";
    remote = "us-texas.privacy.network";
  }
  { id = "PIA - Portugal";
    uuid = "4cd961a6-df78-5b23-bc42-666f131a1d6a";
    remote = "pt.privacy.network";
  }
  { id = "PIA - Algeria";
    uuid = "c04cb95a-5e61-537d-ae44-7cccf747ce96";
    remote = "dz.privacy.network";
  }
  { id = "PIA - Guatemala";
    uuid = "49dbf47a-9218-51d3-97c4-aa8e7cd7824e";
    remote = "gt-guatemala-pf.privacy.network";
  }
  { id = "PIA - Malta";
    uuid = "5eab987c-d745-5180-8e24-d4be489aa123";
    remote = "malta.privacy.network";
  }
  { id = "PIA - North Macedonia";
    uuid = "6ee2be28-525e-537d-97ff-af9ecb87ae42";
    remote = "mk.privacy.network";
  }
  { id = "PIA - Kazakhstan";
    uuid = "d8f85fd1-3561-5982-82dd-06df9f6fa578";
    remote = "kazakhstan.privacy.network";
  }
  { id = "PIA - US Maine";
    uuid = "328c6732-bab6-5920-b125-38b048fca3e5";
    remote = "us-maine-pf.privacy.network";
  }
  { id = "PIA - US Mississippi";
    uuid = "3a7b4ba2-2cbf-58f0-8f9c-56dc77c1f6eb";
    remote = "us-mississippi-pf.privacy.network";
  }
  { id = "PIA - United Arab Emirates";
    uuid = "a4cc3673-a772-5cb6-81e1-3d534cfc7cc7";
    remote = "ae.privacy.network";
  }
  { id = "PIA - Egypt";
    uuid = "3b04c106-261b-5f86-90f7-677e3c252ca9";
    remote = "egypt.privacy.network";
  }
  { id = "PIA - Slovenia";
    uuid = "c8934dcb-e96e-5b06-ba6b-bb61ba0d95a4";
    remote = "slovenia.privacy.network";
  }
  { id = "PIA - South Africa";
    uuid = "a00db795-5e48-5abd-b28a-87048d530123";
    remote = "za.privacy.network";
  }
  { id = "PIA - Moldova";
    uuid = "dcf2692d-06b2-543b-82ee-0de0f1493299";
    remote = "md.privacy.network";
  }
  { id = "PIA - Philippines";
    uuid = "5a5f46d3-a356-54f7-b2f6-45a16565ad18";
    remote = "philippines.privacy.network";
  }
  { id = "PIA - US Virginia";
    uuid = "3af55bd5-ba87-5584-b46c-f2dbae72e2ae";
    remote = "us-virginia-pf.privacy.network";
  }
  { id = "PIA - Israel";
    uuid = "615eb8f7-af22-50a8-99de-a338244a2ac3";
    remote = "israel.privacy.network";
  }
  { id = "PIA - Slovakia";
    uuid = "d62a5faf-7b30-5d53-a2ff-e077242fc74a";
    remote = "sk.privacy.network";
  }
  { id = "PIA - US Michigan";
    uuid = "8ebe822b-e160-5c64-acfd-7a18df1e501c";
    remote = "us-michigan-pf.privacy.network";
  }
  { id = "PIA - US Baltimore";
    uuid = "fa40e318-b482-585e-9fb6-cb029e5bb88a";
    remote = "us-baltimore.privacy.network";
  }
  { id = "PIA - Argentina";
    uuid = "21299003-1903-5b0e-9baa-9b6f620de7e1";
    remote = "ar.privacy.network";
  }
  { id = "PIA - US Rhode Island";
    uuid = "40d908cc-d5d5-585a-82ec-c61a1d4f37f5";
    remote = "us-rhode-island-pf.privacy.network";
  }
  { id = "PIA - JP Streaming Optimized";
    uuid = "2b618a89-5743-5f61-8328-2f0369b9d919";
    remote = "japan-2.privacy.network";
  }
  { id = "PIA - CA Ontario Streaming Optimized";
    uuid = "05810f61-a360-5ae5-a6e2-b8820740d73b";
    remote = "ca-ontario-so.privacy.network";
  }
  { id = "PIA - DE Berlin";
    uuid = "0a2efb24-8b78-5dff-acbe-aaebd4f8e6ce";
    remote = "de-berlin.privacy.network";
  }
  { id = "PIA - Estonia";
    uuid = "6c5c17c6-1737-5ff9-8aab-630260408f83";
    remote = "ee.privacy.network";
  }
  { id = "PIA - Switzerland";
    uuid = "99794b47-8be5-566a-bcbe-fdfcc0e0d909";
    remote = "swiss.privacy.network";
  }
  { id = "PIA - US Washington DC";
    uuid = "a885fd99-05db-5b28-baea-6322593251af";
    remote = "us-washingtondc.privacy.network";
  }
  { id = "PIA - Vietnam";
    uuid = "95c0dae5-14bd-5bae-bd3e-088ca292a92f";
    remote = "vietnam.privacy.network";
  }
  { id = "PIA - US East Streaming Optimized";
    uuid = "c10a7080-c929-57dd-aedd-8b87223663ec";
    remote = "us-streaming.privacy.network";
  }
  { id = "PIA - Singapore";
    uuid = "aba38b0f-39af-5431-a97a-c43cefdf27ff";
    remote = "sg.privacy.network";
  }
  { id = "PIA - DK Streaming Optimized";
    uuid = "f48bcaa6-a4a6-5710-89b2-77ef4f6e7d67";
    remote = "denmark-2.privacy.network";
  }
  { id = "PIA - Costa Rica";
    uuid = "a507f6a5-43ac-5708-8f35-3251df13442d";
    remote = "sanjose.privacy.network";
  }
  { id = "PIA - CA Montreal";
    uuid = "0b424bd4-4a79-5c2a-909d-6210943084b1";
    remote = "ca-montreal.privacy.network";
  }
]