# Generated by ./modules/nixos/pia/pia-server-list-generator.sh

[
  { id = "PIA - Georgia";
    uuid = "";
    remote = "georgia.privacy.network";
  }
  { id = "PIA - France";
    uuid = "";
    remote = "france.privacy.network";
  }
  { id = "PIA - US Silicon Valley";
    uuid = "";
    remote = "us-siliconvalley.privacy.network";
  }
  { id = "PIA - US South Dakota";
    uuid = "";
    remote = "us-south-dakota-pf.privacy.network";
  }
  { id = "PIA - Monaco";
    uuid = "";
    remote = "monaco.privacy.network";
  }
  { id = "PIA - DE Germany Streaming Optimized";
    uuid = "";
    remote = "de-germany-so.privacy.network";
  }
  { id = "PIA - Croatia";
    uuid = "";
    remote = "zagreb.privacy.network";
  }
  { id = "PIA - US East Streaming Optimized";
    uuid = "";
    remote = "us-streaming.privacy.network";
  }
  { id = "PIA - US Arkansas";
    uuid = "";
    remote = "us-arkansas-pf.privacy.network";
  }
  { id = "PIA - ES Valencia";
    uuid = "";
    remote = "es-valencia.privacy.network";
  }
  { id = "PIA - IT Milano";
    uuid = "";
    remote = "italy.privacy.network";
  }
  { id = "PIA - Portugal";
    uuid = "";
    remote = "pt.privacy.network";
  }
  { id = "PIA - DK Copenhagen";
    uuid = "";
    remote = "denmark.privacy.network";
  }
  { id = "PIA - Austria";
    uuid = "";
    remote = "austria.privacy.network";
  }
  { id = "PIA - Venezuela";
    uuid = "";
    remote = "venezuela.privacy.network";
  }
  { id = "PIA - Colombia";
    uuid = "";
    remote = "bogota.privacy.network";
  }
  { id = "PIA - Morocco";
    uuid = "";
    remote = "morocco.privacy.network";
  }
  { id = "PIA - Argentina";
    uuid = "";
    remote = "ar.privacy.network";
  }
  { id = "PIA - US Seattle";
    uuid = "";
    remote = "us-seattle.privacy.network";
  }
  { id = "PIA - US Denver";
    uuid = "";
    remote = "us-denver.privacy.network";
  }
  { id = "PIA - AU Melbourne";
    uuid = "";
    remote = "aus-melbourne.privacy.network";
  }
  { id = "PIA - Taiwan";
    uuid = "";
    remote = "taiwan.privacy.network";
  }
  { id = "PIA - Kazakhstan";
    uuid = "";
    remote = "kazakhstan.privacy.network";
  }
  { id = "PIA - CA Ontario Streaming Optimized";
    uuid = "";
    remote = "ca-ontario-so.privacy.network";
  }
  { id = "PIA - Guatemala";
    uuid = "";
    remote = "gt-guatemala-pf.privacy.network";
  }
  { id = "PIA - Uruguay";
    uuid = "";
    remote = "uy-uruguay-pf.privacy.network";
  }
  { id = "PIA - US Oklahoma";
    uuid = "";
    remote = "us-oklahoma-pf.privacy.network";
  }
  { id = "PIA - Slovakia";
    uuid = "";
    remote = "sk.privacy.network";
  }
  { id = "PIA - United Arab Emirates";
    uuid = "";
    remote = "ae.privacy.network";
  }
  { id = "PIA - Philippines";
    uuid = "";
    remote = "philippines.privacy.network";
  }
  { id = "PIA - IT Streaming Optimized";
    uuid = "";
    remote = "italy-2.privacy.network";
  }
  { id = "PIA - US Mississippi";
    uuid = "";
    remote = "us-mississippi-pf.privacy.network";
  }
  { id = "PIA - JP Streaming Optimized";
    uuid = "";
    remote = "japan-2.privacy.network";
  }
  { id = "PIA - Ukraine";
    uuid = "";
    remote = "ua.privacy.network";
  }
  { id = "PIA - Serbia";
    uuid = "";
    remote = "rs.privacy.network";
  }
  { id = "PIA - US Baltimore";
    uuid = "";
    remote = "us-baltimore.privacy.network";
  }
  { id = "PIA - DE Frankfurt";
    uuid = "";
    remote = "de-frankfurt.privacy.network";
  }
  { id = "PIA - Malta";
    uuid = "";
    remote = "malta.privacy.network";
  }
  { id = "PIA - Isle of Man";
    uuid = "";
    remote = "man.privacy.network";
  }
  { id = "PIA - Chile";
    uuid = "";
    remote = "santiago.privacy.network";
  }
  { id = "PIA - US New Hampshire";
    uuid = "";
    remote = "us-new-hampshire-pf.privacy.network";
  }
  { id = "PIA - SE Streaming Optimized";
    uuid = "";
    remote = "sweden-2.privacy.network";
  }
  { id = "PIA - US Maine";
    uuid = "";
    remote = "us-maine-pf.privacy.network";
  }
  { id = "PIA - NL Netherlands Streaming Optimized";
    uuid = "";
    remote = "nl-netherlands-so.privacy.network";
  }
  { id = "PIA - US Virginia";
    uuid = "";
    remote = "us-virginia-pf.privacy.network";
  }
  { id = "PIA - Slovenia";
    uuid = "";
    remote = "slovenia.privacy.network";
  }
  { id = "PIA - Brazil";
    uuid = "";
    remote = "br.privacy.network";
  }
  { id = "PIA - Mexico";
    uuid = "";
    remote = "mexico.privacy.network";
  }
  { id = "PIA - Qatar";
    uuid = "";
    remote = "qatar.privacy.network";
  }
  { id = "PIA - AU Sydney";
    uuid = "";
    remote = "au-sydney.privacy.network";
  }
  { id = "PIA - Hungary";
    uuid = "";
    remote = "hungary.privacy.network";
  }
  { id = "PIA - Moldova";
    uuid = "";
    remote = "md.privacy.network";
  }
  { id = "PIA - US West";
    uuid = "";
    remote = "us3.privacy.network";
  }
  { id = "PIA - Mongolia";
    uuid = "";
    remote = "mongolia.privacy.network";
  }
  { id = "PIA - Andorra";
    uuid = "";
    remote = "ad.privacy.network";
  }
  { id = "PIA - Bahamas";
    uuid = "";
    remote = "bahamas.privacy.network";
  }
  { id = "PIA - US Tennessee";
    uuid = "";
    remote = "us-tennessee-pf.privacy.network";
  }
  { id = "PIA - Norway";
    uuid = "";
    remote = "no.privacy.network";
  }
  { id = "PIA - US Nebraska";
    uuid = "";
    remote = "us-nebraska-pf.privacy.network";
  }
  { id = "PIA - US Rhode Island";
    uuid = "";
    remote = "us-rhode-island-pf.privacy.network";
  }
  { id = "PIA - US Wilmington";
    uuid = "";
    remote = "us-wilmington.privacy.network";
  }
  { id = "PIA - US West Virginia";
    uuid = "";
    remote = "us-west-virginia-pf.privacy.network";
  }
  { id = "PIA - US Idaho";
    uuid = "";
    remote = "us-idaho-pf.privacy.network";
  }
  { id = "PIA - US Connecticut";
    uuid = "";
    remote = "us-connecticut-pf.privacy.network";
  }
  { id = "PIA - CA Montreal";
    uuid = "";
    remote = "ca-montreal.privacy.network";
  }
  { id = "PIA - Turkey";
    uuid = "";
    remote = "tr.privacy.network";
  }
  { id = "PIA - US Florida";
    uuid = "";
    remote = "us-florida.privacy.network";
  }
  { id = "PIA - Macao";
    uuid = "";
    remote = "macau.privacy.network";
  }
  { id = "PIA - New Zealand";
    uuid = "";
    remote = "nz.privacy.network";
  }
  { id = "PIA - US East";
    uuid = "";
    remote = "us-newjersey.privacy.network";
  }
  { id = "PIA - US West Streaming Optimized";
    uuid = "";
    remote = "us-streaming-2.privacy.network";
  }
  { id = "PIA - Ecuador";
    uuid = "";
    remote = "ec-ecuador-pf.privacy.network";
  }
  { id = "PIA - US New York";
    uuid = "";
    remote = "us-newyorkcity.privacy.network";
  }
  { id = "PIA - UK Southampton";
    uuid = "";
    remote = "uk-southampton.privacy.network";
  }
  { id = "PIA - US Pennsylvania";
    uuid = "";
    remote = "us-pennsylvania-pf.privacy.network";
  }
  { id = "PIA - US Las Vegas";
    uuid = "";
    remote = "us-lasvegas.privacy.network";
  }
  { id = "PIA - CA Toronto";
    uuid = "";
    remote = "ca-toronto.privacy.network";
  }
  { id = "PIA - US Missouri";
    uuid = "";
    remote = "us-missouri-pf.privacy.network";
  }
  { id = "PIA - Montenegro";
    uuid = "";
    remote = "montenegro.privacy.network";
  }
  { id = "PIA - US Iowa";
    uuid = "";
    remote = "us-iowa-pf.privacy.network";
  }
  { id = "PIA - US Minnesota";
    uuid = "";
    remote = "us-minnesota-pf.privacy.network";
  }
  { id = "PIA - Sri Lanka";
    uuid = "";
    remote = "srilanka.privacy.network";
  }
  { id = "PIA - US Salt Lake City";
    uuid = "";
    remote = "us-saltlakecity.privacy.network";
  }
  { id = "PIA - Poland";
    uuid = "";
    remote = "poland.privacy.network";
  }
  { id = "PIA - CA Ontario";
    uuid = "";
    remote = "ca-ontario.privacy.network";
  }
  { id = "PIA - Malaysia";
    uuid = "";
    remote = "kualalumpur.privacy.network";
  }
  { id = "PIA - US Indiana";
    uuid = "";
    remote = "us-indiana-pf.privacy.network";
  }
  { id = "PIA - Greece";
    uuid = "";
    remote = "gr.privacy.network";
  }
  { id = "PIA - US Chicago";
    uuid = "";
    remote = "us-chicago.privacy.network";
  }
  { id = "PIA - US Michigan";
    uuid = "";
    remote = "us-michigan-pf.privacy.network";
  }
  { id = "PIA - Switzerland";
    uuid = "";
    remote = "swiss.privacy.network";
  }
  { id = "PIA - US Ohio";
    uuid = "";
    remote = "us-ohio-pf.privacy.network";
  }
  { id = "PIA - JP Tokyo";
    uuid = "";
    remote = "japan.privacy.network";
  }
  { id = "PIA - US Atlanta";
    uuid = "";
    remote = "us-atlanta.privacy.network";
  }
  { id = "PIA - Vietnam";
    uuid = "";
    remote = "vietnam.privacy.network";
  }
  { id = "PIA - Luxembourg";
    uuid = "";
    remote = "lu.privacy.network";
  }
  { id = "PIA - Cyprus";
    uuid = "";
    remote = "cyprus.privacy.network";
  }
  { id = "PIA - Bosnia and Herzegovina";
    uuid = "";
    remote = "ba.privacy.network";
  }
  { id = "PIA - Netherlands";
    uuid = "";
    remote = "nl-amsterdam.privacy.network";
  }
  { id = "PIA - Romania";
    uuid = "";
    remote = "ro.privacy.network";
  }
  { id = "PIA - UK Manchester";
    uuid = "";
    remote = "uk-manchester.privacy.network";
  }
  { id = "PIA - US Texas";
    uuid = "";
    remote = "us-texas.privacy.network";
  }
  { id = "PIA - US South Carolina";
    uuid = "";
    remote = "us-south-carolina-pf.privacy.network";
  }
  { id = "PIA - US Montana";
    uuid = "";
    remote = "us-montana-pf.privacy.network";
  }
  { id = "PIA - ES Madrid";
    uuid = "";
    remote = "spain.privacy.network";
  }
  { id = "PIA - Czech Republic";
    uuid = "";
    remote = "czech.privacy.network";
  }
  { id = "PIA - US Oregon";
    uuid = "";
    remote = "us-oregon-pf.privacy.network";
  }
  { id = "PIA - SE Stockholm";
    uuid = "";
    remote = "sweden.privacy.network";
  }
  { id = "PIA - Algeria";
    uuid = "";
    remote = "dz.privacy.network";
  }
  { id = "PIA - Ireland";
    uuid = "";
    remote = "ireland.privacy.network";
  }
  { id = "PIA - US Wyoming";
    uuid = "";
    remote = "us-wyoming-pf.privacy.network";
  }
  { id = "PIA - FI Helsinki";
    uuid = "";
    remote = "fi.privacy.network";
  }
  { id = "PIA - UK Streaming Optimized";
    uuid = "";
    remote = "uk-2.privacy.network";
  }
  { id = "PIA - US North Dakota";
    uuid = "";
    remote = "us-north-dakota-pf.privacy.network";
  }
  { id = "PIA - Australia Streaming Optimized";
    uuid = "";
    remote = "au-australia-so.privacy.network";
  }
  { id = "PIA - US Louisiana";
    uuid = "";
    remote = "us-louisiana-pf.privacy.network";
  }
  { id = "PIA - Nepal";
    uuid = "";
    remote = "np-nepal-pf.privacy.network";
  }
  { id = "PIA - Latvia";
    uuid = "";
    remote = "lv.privacy.network";
  }
  { id = "PIA - CA Vancouver";
    uuid = "";
    remote = "ca-vancouver.privacy.network";
  }
  { id = "PIA - US Alabama";
    uuid = "";
    remote = "us-alabama-pf.privacy.network";
  }
  { id = "PIA - AU Adelaide";
    uuid = "";
    remote = "au-adelaide-pf.privacy.network";
  }
  { id = "PIA - US Wisconsin";
    uuid = "";
    remote = "us-wisconsin-pf.privacy.network";
  }
  { id = "PIA - Albania";
    uuid = "";
    remote = "al.privacy.network";
  }
  { id = "PIA - Cambodia";
    uuid = "";
    remote = "cambodia.privacy.network";
  }
  { id = "PIA - Singapore";
    uuid = "";
    remote = "sg.privacy.network";
  }
  { id = "PIA - US Kentucky";
    uuid = "";
    remote = "us-kentucky-pf.privacy.network";
  }
  { id = "PIA - DE Berlin";
    uuid = "";
    remote = "de-berlin.privacy.network";
  }
  { id = "PIA - South Korea";
    uuid = "";
    remote = "kr-south-korea-pf.privacy.network";
  }
  { id = "PIA - Lithuania";
    uuid = "";
    remote = "lt.privacy.network";
  }
  { id = "PIA - US Washington DC";
    uuid = "";
    remote = "us-washingtondc.privacy.network";
  }
  { id = "PIA - US New Mexico";
    uuid = "";
    remote = "us-new-mexico-pf.privacy.network";
  }
  { id = "PIA - US Houston";
    uuid = "";
    remote = "us-houston.privacy.network";
  }
  { id = "PIA - US Alaska";
    uuid = "";
    remote = "us-alaska-pf.privacy.network";
  }
  { id = "PIA - Iceland";
    uuid = "";
    remote = "is.privacy.network";
  }
  { id = "PIA - UK London";
    uuid = "";
    remote = "uk-london.privacy.network";
  }
  { id = "PIA - Panama";
    uuid = "";
    remote = "panama.privacy.network";
  }
  { id = "PIA - Bulgaria";
    uuid = "";
    remote = "sofia.privacy.network";
  }
  { id = "PIA - US Honolulu";
    uuid = "";
    remote = "us-honolulu.privacy.network";
  }
  { id = "PIA - Bolivia";
    uuid = "";
    remote = "bo-bolivia-pf.privacy.network";
  }
  { id = "PIA - AU Perth";
    uuid = "";
    remote = "aus-perth.privacy.network";
  }
  { id = "PIA - AU Brisbane";
    uuid = "";
    remote = "au-brisbane-pf.privacy.network";
  }
  { id = "PIA - Belgium";
    uuid = "";
    remote = "brussels.privacy.network";
  }
  { id = "PIA - Peru";
    uuid = "";
    remote = "pe-peru-pf.privacy.network";
  }
  { id = "PIA - Costa Rica";
    uuid = "";
    remote = "sanjose.privacy.network";
  }
  { id = "PIA - South Africa";
    uuid = "";
    remote = "za.privacy.network";
  }
  { id = "PIA - India";
    uuid = "";
    remote = "in.privacy.network";
  }
  { id = "PIA - US Massachusetts";
    uuid = "";
    remote = "us-massachusetts-pf.privacy.network";
  }
  { id = "PIA - FI Streaming Optimized";
    uuid = "";
    remote = "fi-2.privacy.network";
  }
  { id = "PIA - Estonia";
    uuid = "";
    remote = "ee.privacy.network";
  }
  { id = "PIA - US Vermont";
    uuid = "";
    remote = "us-vermont-pf.privacy.network";
  }
  { id = "PIA - Israel";
    uuid = "";
    remote = "israel.privacy.network";
  }
  { id = "PIA - Egypt";
    uuid = "";
    remote = "egypt.privacy.network";
  }
  { id = "PIA - China";
    uuid = "";
    remote = "china.privacy.network";
  }
  { id = "PIA - Saudi Arabia";
    uuid = "";
    remote = "saudiarabia.privacy.network";
  }
  { id = "PIA - Hong Kong";
    uuid = "";
    remote = "hk.privacy.network";
  }
  { id = "PIA - Liechtenstein";
    uuid = "";
    remote = "liechtenstein.privacy.network";
  }
  { id = "PIA - US California";
    uuid = "";
    remote = "us-california.privacy.network";
  }
  { id = "PIA - US North Carolina";
    uuid = "";
    remote = "us-north-carolina-pf.privacy.network";
  }
  { id = "PIA - Armenia";
    uuid = "";
    remote = "yerevan.privacy.network";
  }
  { id = "PIA - Nigeria";
    uuid = "";
    remote = "nigeria.privacy.network";
  }
  { id = "PIA - Greenland";
    uuid = "";
    remote = "greenland.privacy.network";
  }
  { id = "PIA - Bangladesh";
    uuid = "";
    remote = "bangladesh.privacy.network";
  }
  { id = "PIA - DK Streaming Optimized";
    uuid = "";
    remote = "denmark-2.privacy.network";
  }
  { id = "PIA - North Macedonia";
    uuid = "";
    remote = "mk.privacy.network";
  }
  { id = "PIA - US Kansas";
    uuid = "";
    remote = "us-kansas-pf.privacy.network";
  }
  { id = "PIA - Indonesia";
    uuid = "";
    remote = "jakarta.privacy.network";
  }
]